-- Collaboration continuity service schema.
-- These tables model the first-pass domain for status-aware collaboration,
-- handover tracking, question routing, and reusable knowledge capture.

create table if not exists collab_team (
    id bigint generated by default as identity primary key,
    team_code varchar(64) not null unique,
    name varchar(128) not null,
    description varchar(500),
    active boolean not null default true
);

create table if not exists collab_user (
    id bigint generated by default as identity primary key,
    employee_number varchar(64) not null unique,
    name varchar(100) not null,
    email varchar(255) not null unique,
    role_title varchar(128),
    user_role varchar(32) not null default 'MEMBER',
    password_hash varchar(255),
    primary_team_id bigint,
    active boolean not null default true,
    constraint fk_collab_user_team foreign key (primary_team_id) references collab_team (id)
);

alter table collab_user add column if not exists password_hash varchar(255);
alter table collab_user add column if not exists user_role varchar(32) default 'MEMBER';

create table if not exists collab_signup_request (
    id bigint generated by default as identity primary key,
    employee_number varchar(64) not null unique,
    name varchar(100) not null,
    email varchar(255) not null unique,
    role_title varchar(128),
    requested_team_code varchar(64),
    requested_team_name varchar(128),
    user_role varchar(32) not null,
    password_hash varchar(255) not null,
    request_status varchar(32) not null,
    review_note varchar(500),
    created_at timestamp not null,
    reviewed_at timestamp,
    reviewed_by_user_id bigint,
    constraint fk_collab_signup_reviewed_by foreign key (reviewed_by_user_id) references collab_user (id)
);

create index if not exists idx_collab_signup_status on collab_signup_request (request_status);

create index if not exists idx_collab_user_team on collab_user (primary_team_id);

create table if not exists collab_user_status (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    availability_status varchar(32) not null,
    status_message varchar(500),
    substitute_user_id bigint,
    available_from timestamp,
    available_until timestamp,
    last_updated_at timestamp not null,
    constraint fk_collab_status_user foreign key (user_id) references collab_user (id),
    constraint fk_collab_status_substitute foreign key (substitute_user_id) references collab_user (id)
);

create index if not exists idx_collab_status_user on collab_user_status (user_id);
create index if not exists idx_collab_status_availability on collab_user_status (availability_status);

create table if not exists collab_work_item (
    id bigint generated by default as identity primary key,
    work_code varchar(64) not null unique,
    title varchar(255) not null,
    summary text,
    owning_team_id bigint not null,
    primary_assignee_id bigint,
    backup_assignee_id bigint,
    work_status varchar(32) not null,
    priority varchar(32) not null,
    due_date date,
    critical_knowledge_risk boolean not null default false,
    needs_handover boolean not null default false,
    last_reviewed_at timestamp,
    constraint fk_collab_work_team foreign key (owning_team_id) references collab_team (id),
    constraint fk_collab_work_primary foreign key (primary_assignee_id) references collab_user (id),
    constraint fk_collab_work_backup foreign key (backup_assignee_id) references collab_user (id)
);

create index if not exists idx_collab_work_team on collab_work_item (owning_team_id);
create index if not exists idx_collab_work_status on collab_work_item (work_status);
create index if not exists idx_collab_work_priority on collab_work_item (priority);

create table if not exists collab_work_assignment (
    id bigint generated by default as identity primary key,
    work_item_id bigint not null,
    assignee_id bigint not null,
    assignment_type varchar(32) not null,
    note varchar(500),
    constraint fk_collab_assignment_work foreign key (work_item_id) references collab_work_item (id),
    constraint fk_collab_assignment_user foreign key (assignee_id) references collab_user (id)
);

create index if not exists idx_collab_assignment_work on collab_work_assignment (work_item_id);
create index if not exists idx_collab_assignment_user on collab_work_assignment (assignee_id);

create table if not exists collab_handover_document (
    id bigint generated by default as identity primary key,
    work_item_id bigint not null,
    author_id bigint not null,
    title varchar(255) not null,
    current_state_summary text,
    pending_actions text,
    related_systems varchar(500),
    key_contacts varchar(500),
    handover_notes text,
    risk_notes text,
    created_at timestamp not null,
    updated_at timestamp not null,
    last_verified_at timestamp,
    constraint fk_collab_handover_work foreign key (work_item_id) references collab_work_item (id),
    constraint fk_collab_handover_author foreign key (author_id) references collab_user (id)
);

create index if not exists idx_collab_handover_work on collab_handover_document (work_item_id);
alter table collab_handover_document add column if not exists key_contacts varchar(500);
alter table collab_handover_document add column if not exists handover_notes text;
alter table collab_handover_document add column if not exists created_at timestamp default current_timestamp;
alter table collab_handover_document add column if not exists updated_at timestamp default current_timestamp;

create table if not exists collab_knowledge_article (
    id bigint generated by default as identity primary key,
    owning_team_id bigint not null,
    author_id bigint not null,
    title varchar(255) not null,
    category varchar(32) not null,
    body_summary text,
    keywords varchar(500),
    related_work_code varchar(64),
    stale_after_date date,
    constraint fk_collab_article_team foreign key (owning_team_id) references collab_team (id),
    constraint fk_collab_article_author foreign key (author_id) references collab_user (id)
);

create index if not exists idx_collab_article_team on collab_knowledge_article (owning_team_id);
create index if not exists idx_collab_article_category on collab_knowledge_article (category);

create table if not exists collab_question_thread (
    id bigint generated by default as identity primary key,
    requested_by_id bigint not null,
    target_team_id bigint,
    target_user_id bigint,
    routed_user_id bigint,
    question_status varchar(32) not null,
    title varchar(255) not null,
    question_body text,
    resolution_summary text,
    source_work_code varchar(64),
    created_at timestamp not null,
    constraint fk_collab_question_requester foreign key (requested_by_id) references collab_user (id),
    constraint fk_collab_question_team foreign key (target_team_id) references collab_team (id),
    constraint fk_collab_question_target_user foreign key (target_user_id) references collab_user (id),
    constraint fk_collab_question_routed_user foreign key (routed_user_id) references collab_user (id)
);

create index if not exists idx_collab_question_status on collab_question_thread (question_status);
create index if not exists idx_collab_question_target_user on collab_question_thread (target_user_id);

create table if not exists collab_question_answer (
    id bigint generated by default as identity primary key,
    question_thread_id bigint not null,
    answered_by_id bigint not null,
    answer_body text,
    accepted boolean not null default false,
    created_at timestamp not null,
    constraint fk_collab_answer_thread foreign key (question_thread_id) references collab_question_thread (id),
    constraint fk_collab_answer_user foreign key (answered_by_id) references collab_user (id)
);

create index if not exists idx_collab_answer_thread on collab_question_answer (question_thread_id);

create table if not exists collab_decision_log (
    id bigint generated by default as identity primary key,
    work_item_id bigint not null,
    author_id bigint not null,
    decision_title varchar(255) not null,
    decision_context text,
    decision_outcome text,
    follow_up_action text,
    created_at timestamp not null,
    constraint fk_collab_decision_work foreign key (work_item_id) references collab_work_item (id),
    constraint fk_collab_decision_author foreign key (author_id) references collab_user (id)
);

create index if not exists idx_collab_decision_work on collab_decision_log (work_item_id);

create table if not exists collab_notification (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    notification_type varchar(32) not null,
    title varchar(255) not null,
    body text,
    read boolean not null default false,
    link_path varchar(255),
    created_at timestamp not null,
    constraint fk_collab_notification_user foreign key (user_id) references collab_user (id)
);

create index if not exists idx_collab_notification_user on collab_notification (user_id);
create index if not exists idx_collab_notification_read on collab_notification (read);
